### PR TITLE
Update evince to 42.3

### PR DESCRIPTION
**Pull request by rvlobato**
Update:
- evince to 42.3 and add external checker
- gnome-desktop to 42.1 and external checker
- libarchive to 3.6.1

### CODE REVIEW

**Comment by hadess** [comment]
LGTM

**Comment by rvlobato** [comment]
cc @nedrichards, sorry to ping you, since you were the last one to merger here

**Comment by A6GibKm** [comment]
You need to bump the runtime to 42 too.

**Comment by hfiguiere** [comment]
merging since it's LGTM

**Pull request merged**
