### PR TITLE
Add WebP comics support

### PR DESCRIPTION
**Pull request by hadess**
See #10

### CODE REVIEW

**Comment by hadess** [comment]
Tested, and works as expected (I can open the Pepper and Carrot WebP comics just fine)

**Comment by hadess** [comment]
(If that's to your taste, I'd appreciate write access to this repo, I work on the comics backend upstream)

**Comment by nedrichards** [comment]
You got it (I know you work on a bunch of other GNOME stuff upstream across the stack, so just let me know if you need access to that)

**Comment by nedrichards** [comment]
bot, build

**Comment by hadess** [comment]
That worked:
https://flathub.org/builds/#/builders/2/builds/4666
so merging, yay!

**Pull request merged**
